health-check:
  script:
    - fab --version
    - fab -f . --list-format=nested --list
sonar:
  script:
    - /opt/sonar-scanner/bin/sonar-scanner -Dsonar.host.url='https://sonarqube.savoirfairelinux.net' -Dsonar.login='8317c73bde6903c2cca1fbcc2148a937602fbc97' -Dsonar.analysis.mode=preview -Dsonar.issuesReport.console.enable=true     -Dsonar.gitlab.commit_sha=$CI_BUILD_REF -Dsonar.gitlab.ref=$CI_BUILD_REF_NAME


